apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
  labels:
    app: ghost-blog
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost-blog
  template:
    metadata:
      labels:
        app: ghost-blog
    spec:
      serviceAccountName: test-eks-sa
      containers:
      - name: ghost-blog
        image: ghost:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 2368
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 512m
            memory: 256Mi
        startupProbe:
          tcpSocket:
            port: 2368
          periodSeconds: 10
          failureThreshold: 30
        livenessProbe:
          tcpSocket:
            port: 2368
          initialDelaySeconds: 30
          periodSeconds: 90
          timeoutSeconds: 60
        readinessProbe:
          tcpSocket:
            port: 2368
          initialDelaySeconds: 30
          periodSeconds: 60
        livenessProbe:
          httpGet:
            path: /
            port: 2368
          initialDelaySeconds: 3
          periodSeconds: 3
        env:
        - name: url
          value: "https://test-gh.example.com"
        - name: database_client
          value: mysql
        - name: database_connection_port
          value: "3306"
        - name: database_connection_host
          valueFrom:
            secretKeyRef:
              name: db-external-secret
              key: database_connection_host         
        - name: database_connection_user
          valueFrom:
            secretKeyRef:
              name: db-external-secret
              key: database_connection_user
        - name: database_connection_password
          valueFrom:
            secretKeyRef:
              name: db-external-secret
              key: database_connection_password
        - name: database_connection_database
          valueFrom:
            secretKeyRef:
              name: db-external-secret
              key: database_connection_database
        - name: database_connection_ssl
          value: "true"
