apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: db-external-secret
  namespace: test
spec:
  backendType: secretsManager 
  data:
    - key: test-eks/gh-db-secrets
      name: database_connection_password
      property: password
    - key: test-eks/gh-db-secrets
      name: database_connection_user
      property: username
    - key: test-eks/gh-db-secrets
      name: database_connection_host
      property: host
    - key: test-eks/gh-db-secrets
      name: database_connection_database
      property: dbname